#!/bin/bash

echo "=== Monitoring Alerts Setup Script for Chatbot SaaS v2.1 ==="
echo "Configuring email and Slack alerts for monitoring"
echo ""

# Configuration
DOMAIN="cwsv.truyenthongviet.vn"
EMAIL="admin@truyenthongviet.vn"
SLACK_WEBHOOK_URL="YOUR_SLACK_WEBHOOK_URL"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

print_success() {
    echo -e "${GREEN}SUCCESS: $1${NC}"
}

print_error() {
    echo -e "${RED}ERROR: $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}WARNING: $1${NC}"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

print_status "Setting up monitoring alerts configuration"

# Step 1: Create alertmanager templates directory
print_status "Creating alertmanager templates directory"
mkdir -p /etc/alertmanager/templates

# Step 2: Create email template
print_status "Creating email templates"
cat > /etc/alertmanager/templates/email.tmpl << 'EOF'
{{ define "email.default.subject" }}
[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }} - Chatbot SaaS v2.1
{{ end }}

{{ define "email.default.html" }}
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background-color: #f8f9fa; padding: 20px; border-radius: 5px; }
        .alert-critical { background-color: #f8d7da; border: 1px solid #f5c6cb; padding: 15px; border-radius: 5px; margin: 10px 0; }
        .alert-warning { background-color: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; margin: 10px 0; }
        .alert-info { background-color: #d1ecf1; border: 1px solid #bee5eb; padding: 15px; border-radius: 5px; margin: 10px 0; }
        .footer { margin-top: 30px; font-size: 12px; color: #6c757d; }
        table { border-collapse: collapse; width: 100%; margin: 10px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Chatbot SaaS v2.1 Monitoring Alert</h2>
        <p><strong>Status:</strong> {{ .Status | toUpper }}</p>
        <p><strong>Time:</strong> {{ .Alerts.Firing | len }} alert(s) firing</p>
    </div>

    {{ range .Alerts }}
    <div class="alert-{{ .Labels.severity }}">
        <h3>{{ .Annotations.summary }}</h3>
        <p><strong>Description:</strong> {{ .Annotations.description }}</p>
        
        <table>
            <tr><th>Label</th><th>Value</th></tr>
            {{ range .Labels.SortedPairs }}
            <tr><td>{{ .Name }}</td><td>{{ .Value }}</td></tr>
            {{ end }}
        </table>
        
        {{ if .Annotations.runbook_url }}
        <p><strong>Runbook:</strong> <a href="{{ .Annotations.runbook_url }}">View Runbook</a></p>
        {{ end }}
        
        <p><strong>Started:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
        {{ if .EndsAt }}
        <p><strong>Ended:</strong> {{ .EndsAt.Format "2006-01-02 15:04:05" }}</p>
        {{ end }}
    </div>
    {{ end }}

    <div class="footer">
        <p>This alert was generated by Chatbot SaaS v2.1 monitoring system.</p>
        <p>To manage alerts, visit: <a href="https://{{ .ExternalURL }}">Grafana Dashboard</a></p>
    </div>
</body>
</html>
{{ end }}
EOF

# Step 3: Create Slack template
print_status "Creating Slack templates"
cat > /etc/alertmanager/templates/slack.tmpl << 'EOF'
{{ define "slack.default.title" }}
{{ .Status | toUpper }}: {{ .GroupLabels.alertname }}
{{ end }}

{{ define "slack.default.text" }}
{{ range .Alerts }}
*Alert:* {{ .Annotations.summary }}
*Description:* {{ .Annotations.description }}
*Instance:* {{ .Labels.instance }}
*Severity:* {{ .Labels.severity }}
*Started:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
{{ if .Annotations.runbook_url }}
*Runbook:* <{{ .Annotations.runbook_url }}|View Runbook>
{{ end }}
{{ end }}
{{ end }}
EOF

# Step 4: Update alertmanager configuration with Gmail settings
print_status "Configuring Gmail SMTP settings"

# Prompt for Gmail app password
echo ""
print_warning "To send email alerts via Gmail, you need to:"
echo "1. Enable 2-factor authentication on your Gmail account"
echo "2. Generate an App Password: https://myaccount.google.com/apppasswords"
echo "3. Use the App Password below"
echo ""

read -p "Enter your Gmail App Password: " -s GMAIL_PASSWORD
echo ""

if [[ -z "$GMAIL_PASSWORD" ]]; then
    print_error "Gmail App Password is required"
    exit 1
fi

# Update alertmanager.yml with Gmail password
sed -i "s/your_gmail_app_password/$GMAIL_PASSWORD/g" monitoring/alertmanager.yml

# Step 5: Configure Slack webhook (optional)
print_status "Configuring Slack integration (optional)"

read -p "Enter your Slack webhook URL (press Enter to skip): " SLACK_URL_INPUT

if [[ -n "$SLACK_URL_INPUT" ]]; then
    # Update Slack webhook URL in alertmanager.yml
    sed -i "s|YOUR_SLACK_WEBHOOK_URL|$SLACK_URL_INPUT|g" monitoring/alertmanager.yml"
    print_success "Slack webhook configured"
else
    print_warning "Slack integration skipped"
fi

# Step 6: Create monitoring startup script
print_status "Creating monitoring startup script"

cat > start-monitoring-with-alerts.sh << 'EOF'
#!/bin/bash

echo "=== Starting Chatbot SaaS v2.1 Monitoring with Alerts ==="

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo "ERROR: Docker is not running"
    exit 1
fi

# Create monitoring network if not exists
docker network create chatbot_saas_monitoring 2>/dev/null

# Start monitoring stack with alerts
docker-compose -f docker-compose.monitoring.yml up -d

# Wait for services to start
echo "Waiting for services to start..."
sleep 30

# Check service health
echo "Checking service health..."
docker-compose -f docker-compose.monitoring.yml ps

# Display URLs
echo ""
echo "=== Monitoring URLs ==="
echo "Prometheus: http://localhost:9090"
echo "Grafana: http://localhost:3000 (admin/Admin_2025!)"
echo "Alertmanager: http://localhost:9093"
echo "Node Exporter: http://localhost:9100/metrics"
echo ""

# Test alertmanager configuration
echo "Testing Alertmanager configuration..."
if curl -s http://localhost:9093/-/healthy > /dev/null; then
    echo "SUCCESS: Alertmanager is healthy"
else
    echo "WARNING: Alertmanager may not be ready yet"
fi

echo ""
echo "=== Alert Configuration ==="
echo "Email alerts: admin@truyenthongviet.vn"
echo "Slack alerts: $(grep -c "slack_configs" monitoring/alertmanager.yml) channels configured"
echo "Alert rules: $(grep -c "alert:" monitoring/alert-rules.yml) rules defined"
echo ""

echo "=== Next Steps ==="
echo "1. Access Grafana and configure dashboards"
echo "2. Test alert rules by triggering conditions"
echo "3. Verify email and Slack notifications"
echo "4. Set up additional alert channels if needed"

echo ""
echo "Monitoring started successfully!"
EOF

chmod +x start-monitoring-with-alerts.sh

# Step 7: Create alert testing script
print_status "Creating alert testing script"

cat > test-alerts.sh << 'EOF'
#!/bin/bash

echo "=== Testing Chatbot SaaS v2.1 Alerts ==="

# Test alertmanager configuration
echo "Testing Alertmanager configuration..."
if curl -s http://localhost:9093/-/healthy > /dev/null; then
    echo "SUCCESS: Alertmanager is healthy"
else
    echo "ERROR: Alertmanager is not accessible"
    exit 1
fi

# Test Prometheus targets
echo "Testing Prometheus targets..."
PROMETHEUS_URL="http://localhost:9090"

# Check if Prometheus is accessible
if curl -s "$PROMETHEUS_URL/-/healthy" > /dev/null; then
    echo "SUCCESS: Prometheus is healthy"
else
    echo "ERROR: Prometheus is not accessible"
    exit 1
fi

# Check targets
echo "Checking Prometheus targets..."
TARGETS=$(curl -s "$PROMETHEUS_URL/api/v1/targets" | jq -r '.data.activeTargets[] | "\(.labels.job): \(.health)"')

if [[ -n "$TARGETS" ]]; then
    echo "Prometheus targets:"
    echo "$TARGETS"
else
    echo "WARNING: No targets found"
fi

# Test alert rules
echo "Testing alert rules..."
RULES=$(curl -s "$PROMETHEUS_URL/api/v1/rules" | jq -r '.data.groups[].rules[] | "\(.name): \(.state)"')

if [[ -n "$RULES" ]]; then
    echo "Alert rules loaded:"
    echo "$RULES"
else
    echo "WARNING: No alert rules found"
fi

# Send test alert
echo "Sending test alert..."
TEST_ALERT='{
  "labels": {
    "alertname": "TestAlert",
    "severity": "info",
    "service": "chatbot-saas"
  },
  "annotations": {
    "summary": "This is a test alert",
    "description": "Testing the alert notification system"
  }
}'

if curl -s -X POST -H "Content-Type: application/json" -d "$TEST_ALERT" http://localhost:9093/api/v1/alerts > /dev/null; then
    echo "SUCCESS: Test alert sent"
else
    echo "ERROR: Failed to send test alert"
fi

echo ""
echo "=== Alert Testing Complete ==="
echo "Check your email and Slack for test notifications"
echo "Alertmanager UI: http://localhost:9093"
EOF

chmod +x test-alerts.sh

# Step 8: Update docker-compose to include alert rules
print_status "Updating monitoring docker-compose configuration"

# Add alert rules volume to prometheus service
if ! grep -q "alert-rules.yml" docker-compose.monitoring.yml; then
    sed -i '/prometheus.yml/a\      - ./monitoring/alert-rules.yml:/etc/prometheus/rules/alert-rules.yml' docker-compose.monitoring.yml"
fi

# Add alert rules directory
if ! grep -q "rules:" docker-compose.monitoring.yml; then
    sed -i '/monitoring\/prometheus.yml/a\      - ./monitoring/rules:/etc/prometheus/rules' docker-compose.monitoring.yml"
fi

# Step 9: Create monitoring documentation
print_status "Creating monitoring documentation"

cat > MONITORING_SETUP.md << EOF
# Monitoring and Alerts Setup Guide

## Overview
Chatbot SaaS v2.1 includes comprehensive monitoring and alerting with Prometheus, Grafana, and Alertmanager.

## Quick Start

### 1. Start Monitoring Stack
\`\`\`bash
./start-monitoring-with-alerts.sh
\`\`\`

### 2. Test Alerts
\`\`\`bash
./test-alerts.sh
\`\`\`

### 3. Access Dashboards
- **Prometheus**: http://localhost:9090
- **Grafana**: http://localhost:3000 (admin/Admin_2025!)
- **Alertmanager**: http://localhost:9093

## Alert Configuration

### Email Alerts
- **From**: alerts@truyenthongviet.vn
- **To**: admin@truyenthongviet.vn, devops@truyenthongviet.vn
- **Provider**: Gmail SMTP

### Slack Alerts
- **Channel**: #alerts-critical (for critical alerts)
- **Webhook**: Configured during setup

### Alert Severities
- **Critical**: Immediate notification (email + Slack)
- **Warning**: Email only, 2-hour repeat interval
- **Info**: Business metrics, 4-hour repeat interval

## Alert Categories

### Application Health
- Application down
- High error rate (>10%)
- High response time (>1s)
- Database connection failures

### Infrastructure
- High CPU usage (>80%)
- High memory usage (>85%)
- Low disk space (>90% critical, >80% warning)

### Database
- PostgreSQL down
- Too many connections (>150)
- Slow queries (>0.5s avg)
- Replication lag (>60s)

### Business Metrics
- Low user activity
- High chatbot usage
- Payment failures
- User registration spikes

### Security
- High failed login rate
- Suspicious API usage
- SSL certificate expiration

## Customization

### Adding New Alerts
1. Edit \`monitoring/alert-rules.yml\`
2. Add new alert rules
3. Restart Prometheus: \`docker-compose restart prometheus\`

### Modifying Notification Channels
1. Edit \`monitoring/alertmanager.yml\`
2. Update receiver configurations
3. Restart Alertmanager: \`docker-compose restart alertmanager\`

### Custom Email Templates
1. Edit \`/etc/alertmanager/templates/email.tmpl\`
2. Restart Alertmanager

## Troubleshooting

### Common Issues

#### 1. Email Not Sending
- Check Gmail App Password
- Verify SMTP settings
- Check Alertmanager logs: \`docker logs alertmanager\`

#### 2. Slack Not Receiving Alerts
- Verify webhook URL
- Check Slack channel permissions
- Test webhook manually

#### 3. Alerts Not Firing
- Check Prometheus targets: \`curl http://localhost:9090/api/v1/targets\`
- Verify alert rules syntax
- Check Alertmanager configuration

### Log Locations
- Prometheus: \`docker logs prometheus\`
- Alertmanager: \`docker logs alertmanager\`
- Grafana: \`docker logs grafana\`

## Maintenance

### Monthly Tasks
1. Review alert rules and thresholds
2. Test notification channels
3. Update SSL certificates
4. Check storage usage

### Quarterly Tasks
1. Review and update dashboards
2. Audit alert configurations
3. Update monitoring stack versions
4. Review retention policies

## Security Considerations

- Gmail App Password should be stored securely
- Slack webhook URLs should be kept secret
- Alertmanager UI should be restricted in production
- Consider using VPN for monitoring access

## Performance Tuning

### Prometheus
- Adjust retention period based on storage needs
- Configure remote write for long-term storage
- Optimize scrape intervals

### Alertmanager
- Tune grouping and routing rules
- Configure silence periods for maintenance
- Set appropriate timeout values

## Integration with Other Services

### PagerDuty
Add PagerDuty integration to Alertmanager for 24/7 on-call:

\`\`\`yaml
pagerduty_configs:
  - routing_key: YOUR_PAGERDUTY_INTEGRATION_KEY
\`\`\`

### Opsgenie
Add Opsgenie integration:

\`\`\`yaml
opsgenie_configs:
  - api_key: YOUR_OPSGENIE_API_KEY
    teams:
      - name: "platform"
\`\`\`

## Support

For monitoring issues:
- Prometheus Documentation: https://prometheus.io/docs/
- Alertmanager Documentation: https://prometheus.io/docs/alerting/latest/alertmanager/
- Grafana Documentation: https://grafana.com/docs/

EOF

print_success "Monitoring alerts setup completed!"

# Display summary
echo ""
print_status "Setup Summary"
echo "=================="
echo "Email alerts configured: admin@truyenthongviet.vn"
echo "Slack integration: $([[ -n "$SLACK_URL_INPUT" ]] && echo "Configured" || echo "Skipped")"
echo "Alert rules loaded: $(grep -c "alert:" monitoring/alert-rules.yml)"
echo "Monitoring scripts created:"
echo "  - start-monitoring-with-alerts.sh"
echo "  - test-alerts.sh"
echo ""
echo "Configuration files:"
echo "  - monitoring/alertmanager.yml"
echo "  - monitoring/alert-rules.yml"
echo "  - /etc/alertmanager/templates/"
echo ""
echo "Next steps:"
echo "1. Run: ./start-monitoring-with-alerts.sh"
echo "2. Test alerts: ./test-alerts.sh"
echo "3. Access dashboards and verify configurations"
echo "4. Customize alert rules and thresholds as needed"
echo ""
print_success "Monitoring alerts are ready to use!"
