package com.chatbot.shared.exceptions;

/**
 * Centralized error code definitions for the entire application.
 * All error codes should be defined here to ensure consistency and avoid duplication.
 */
public enum ErrorCode {
    
    // Common errors
    NOT_FOUND("NOT_FOUND"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    BAD_REQUEST("BAD_REQUEST"),
    CONFLICT("CONFLICT"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    RUNTIME_ERROR("RUNTIME_ERROR"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    TIMEOUT("TIMEOUT"),
    RATE_LIMIT_EXCEEDED("RATE_LIMIT_EXCEEDED"),
    INTEGRATION_ERROR("INTEGRATION_ERROR"),
    ENDPOINT_NOT_FOUND("ENDPOINT_NOT_FOUND"),
    INVALID_REQUEST_BODY("INVALID_REQUEST_BODY"),
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    DATA_INTEGRITY_VIOLATION("DATA_INTEGRITY_VIOLATION"),
    OPTIMISTIC_LOCK("OPTIMISTIC_LOCK"),
    PAYLOAD_TOO_LARGE("PAYLOAD_TOO_LARGE"),
    
    // Authentication errors
    BAD_CREDENTIALS("BAD_CREDENTIALS"),
    AUTHENTICATION_FAILED("AUTHENTICATION_FAILED"),
    INVALID_TOKEN("INVALID_TOKEN"),
    
    // User errors
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    
    // Tenant errors
    TENANT_NOT_FOUND("TENANT_NOT_FOUND"),
    INVALID_TENANT_KEY("INVALID_TENANT_KEY"),
    INSUFFICIENT_PERMISSION("INSUFFICIENT_PERMISSION"),
    TENANT_STATUS_TRANSITION("TENANT_STATUS_TRANSITION"),
    TENANT_PROFILE_ERROR("TENANT_PROFILE_ERROR"),
    TENANT_INACTIVE("TENANT_INACTIVE"),
    ALREADY_MEMBER("ALREADY_MEMBER"),
    JOIN_REQUEST_ALREADY_SENT("JOIN_REQUEST_ALREADY_SENT"),
    INVITATION_PERMISSION_DENIED("INVITATION_PERMISSION_DENIED"),
    CANNOT_ASSIGN_ROLE("CANNOT_ASSIGN_ROLE"),
    USER_NOT_FOUND_FOR_INVITATION("USER_NOT_FOUND_FOR_INVITATION"),
    INVITATION_ALREADY_PENDING("INVITATION_ALREADY_PENDING"),
    INVITATION_INVALID("INVITATION_INVALID"),
    INVITATION_NOT_PENDING("INVITATION_NOT_PENDING"),
    INVITATION_EXPIRED("INVITATION_EXPIRED"),
    CANNOT_ACCEPT_INVITATION("CANNOT_ACCEPT_INVITATION"),
    INVITATION_NOT_FOUND("INVITATION_NOT_FOUND"),
    CANNOT_REJECT_INVITATION("CANNOT_REJECT_INVITATION"),
    CANNOT_REVOKE_INVITATION("CANNOT_REVOKE_INVITATION"),
    INVITATION_NOT_FOUND_IN_TENANT("INVITATION_NOT_FOUND_IN_TENANT"),
    TENANT_CONTEXT_MISSING("TENANT_CONTEXT_MISSING"),
    NOT_TENANT_MEMBER("NOT_TENANT_MEMBER"),
    TENANT_ID_REQUIRED("TENANT_ID_REQUIRED"),
    CANNOT_MANAGE_MEMBERS("CANNOT_MANAGE_MEMBERS"),
    CONNECTION_NOT_FOUND("CONNECTION_NOT_FOUND"),
    CANNOT_VIEW_JOIN_REQUESTS("CANNOT_VIEW_JOIN_REQUESTS"),
    CANNOT_APPROVE_JOIN_REQUESTS("CANNOT_APPROVE_JOIN_REQUESTS"),
    INVALID_STATUS_TRANSITION("INVALID_STATUS_TRANSITION"),
    JOIN_REQUEST_NOT_FOUND("JOIN_REQUEST_NOT_FOUND"),
    CANNOT_CANCEL_OTHERS_REQUEST("CANNOT_CANCEL_OTHERS_REQUEST"),
    CANNOT_CANCEL_NON_PENDING("CANNOT_CANCEL_NON_PENDING"),
    INVALID_JOIN_REQUEST("INVALID_JOIN_REQUEST"),
    CANNOT_CHANGE_OWNER_ROLE("CANNOT_CHANGE_OWNER_ROLE"),
    CANNOT_REMOVE_OWNER("CANNOT_REMOVE_OWNER"),
    USER_NOT_AUTHENTICATED("USER_NOT_AUTHENTICATED"),
    NOT_TENANT_MEMBER_SELF("NOT_TENANT_MEMBER_SELF"),
    OWNER_MUST_TRANSFER("OWNER_MUST_TRANSFER"),
    NOTIFICATION_ERROR("NOTIFICATION_ERROR"),
    CANNOT_ACCESS_TENANT("CANNOT_ACCESS_TENANT"),
    CANNOT_SUSPEND_TENANT("CANNOT_SUSPEND_TENANT"),
    CANNOT_RESUME_TENANT("CANNOT_RESUME_TENANT"),
    CANNOT_DELETE_TENANT("CANNOT_DELETE_TENANT"),
    TENANT_ID_NOT_FOUND("TENANT_ID_NOT_FOUND"),
    CANNOT_UPLOAD_LOGO("CANNOT_UPLOAD_LOGO"),
    CANNOT_UPDATE_LOGO("CANNOT_UPDATE_LOGO"),
    NOT_CONVERSATION_MEMBER("NOT_CONVERSATION_MEMBER"),
    TOKEN_INVALID_OR_EXPIRED("TOKEN_INVALID_OR_EXPIRED"),
    REFRESH_TOKEN_EXPIRED("REFRESH_TOKEN_EXPIRED"),
    CONVERSATION_IDS_REQUIRED("CONVERSATION_IDS_REQUIRED"),
    CANNOT_DELETE_CONVERSATIONS("CANNOT_DELETE_CONVERSATIONS"),
    BULK_DELETE_ERROR("BULK_DELETE_ERROR"),
    CANNOT_UPLOAD_AVATAR("CANNOT_UPLOAD_AVATAR"),
    CANNOT_CREATE_AVATAR_CATEGORY("CANNOT_CREATE_AVATAR_CATEGORY"),
    
    // License errors
    LICENSE_NOT_FOUND("LICENSE_NOT_FOUND"),
    LICENSE_EXPIRED("LICENSE_EXPIRED"),
    LICENSE_INACTIVE("LICENSE_INACTIVE"),
    
    // Payment errors
    PAYMENT_ERROR("PAYMENT_ERROR"),
    PAYMENT_NOT_FOUND("PAYMENT_NOT_FOUND"),
    PAYMENT_EXPIRED("PAYMENT_EXPIRED"),
    INVALID_PAYMENT_AMOUNT("INVALID_PAYMENT_AMOUNT"),
    BANK_API_ERROR("BANK_API_ERROR"),
    
    // Config errors
    CONFIG_NOT_FOUND("CONFIG_NOT_FOUND"),
    CONFIG_ALREADY_EXISTS("CONFIG_ALREADY_EXISTS"),
    CONFIG_READONLY("CONFIG_READONLY"),
    
    // Conversation errors
    CONVERSATION_NOT_FOUND("CONVERSATION_NOT_FOUND"),
    CANNOT_ASSIGN_CONVERSATION("CANNOT_ASSIGN_CONVERSATION"),
    CANNOT_RELEASE_CONVERSATION("CANNOT_RELEASE_CONVERSATION"),
    CANNOT_TAKEOVER_CONVERSATION("CANNOT_TAKEOVER_CONVERSATION"),
    CONVERSATION_ASSIGNED_TO_OTHER("CONVERSATION_ASSIGNED_TO_OTHER"),
    NETWORK_ERROR("NETWORK_ERROR"),
    
    // Resource errors
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND");
    
    private final String code;
    
    ErrorCode(String code) {
        this.code = code;
    }
    
    public String getCode() {
        return code;
    }
    
    @Override
    public String toString() {
        return code;
    }
}
