package com.chatbot.spokes.facebook.webhook.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReferralDto {
    private String ref;
    private String source;
    private String type;
    private String ad_id;
    private String publisher_id;
    private String campaign_id;
    private String adgroup_id;
    private String leadgen_did;
    private String leadgen_form_id;
    private String page_id;
    private String form_id;
    private String is_user_ref;
    private String is_bot_ref;
    private String is_direct_ref;
    private String is_coupon_ref;
    private String is_from_ads;
    private String is_from_messenger_ads;
    private String is_from_messenger_ads_2;
    private String is_from_messenger_ads_3;
    private String is_from_messenger_ads_4;
    private String is_from_messenger_ads_5;
    private String is_from_messenger_ads_6;
    private String is_from_messenger_ads_7;
    private String is_from_messenger_ads_8;
    private String is_from_messenger_ads_9;
    private String is_from_messenger_ads_10;
    private String is_from_messenger_ads_11;
    private String is_from_messenger_ads_12;
    private String is_from_messenger_ads_13;
    private String is_from_messenger_ads_14;
    private String is_from_messenger_ads_15;
    private String is_from_messenger_ads_16;
    private String is_from_messenger_ads_17;
    private String is_from_messenger_ads_18;
    private String is_from_messenger_ads_19;
    private String is_from_messenger_ads_20;
    private String is_from_messenger_ads_21;
    private String is_from_messenger_ads_22;
    private String is_from_messenger_ads_23;
    private String is_from_messenger_ads_24;
    private String is_from_messenger_ads_25;
    private String is_from_messenger_ads_26;
    private String is_from_messenger_ads_27;
    private String is_from_messenger_ads_28;
    private String is_from_messenger_ads_29;
    private String is_from_messenger_ads_30;
    private String is_from_messenger_ads_31;
    private String is_from_messenger_ads_32;
    private String is_from_messenger_ads_33;
    private String is_from_messenger_ads_34;
    private String is_from_messenger_ads_35;
    private String is_from_messenger_ads_36;
    private String is_from_messenger_ads_37;
    private String is_from_messenger_ads_38;
    private String is_from_messenger_ads_39;
    private String is_from_messenger_ads_40;
    private String is_from_messenger_ads_41;
    private String is_from_messenger_ads_42;
    private String is_from_messenger_ads_43;
    private String is_from_messenger_ads_44;
    private String is_from_messenger_ads_45;
    private String is_from_messenger_ads_46;
    private String is_from_messenger_ads_47;
    private String is_from_messenger_ads_48;
    private String is_from_messenger_ads_49;
    private String is_from_messenger_ads_50;
    private String is_from_messenger_ads_51;
    private String is_from_messenger_ads_52;
    private String is_from_messenger_ads_53;
    private String is_from_messenger_ads_54;
    private String is_from_messenger_ads_55;
    private String is_from_messenger_ads_56;
    private String is_from_messenger_ads_57;
    private String is_from_messenger_ads_58;
    private String is_from_messenger_ads_59;
    private String is_from_messenger_ads_60;
    private String is_from_messenger_ads_61;
    private String is_from_messenger_ads_62;
    private String is_from_messenger_ads_63;
    private String is_from_messenger_ads_64;
    private String is_from_messenger_ads_65;
    private String is_from_messenger_ads_66;
    private String is_from_messenger_ads_67;
    private String is_from_messenger_ads_68;
    private String is_from_messenger_ads_69;
    private String is_from_messenger_ads_70;
    private String is_from_messenger_ads_71;
    private String is_from_messenger_ads_72;
    private String is_from_messenger_ads_73;
    private String is_from_messenger_ads_74;
    private String is_from_messenger_ads_75;
    private String is_from_messenger_ads_76;
    private String is_from_messenger_ads_77;
    private String is_from_messenger_ads_78;
    private String is_from_messenger_ads_79;
    private String is_from_messenger_ads_80;
    private String is_from_messenger_ads_81;
    private String is_from_messenger_ads_82;
    private String is_from_messenger_ads_83;
    private String is_from_messenger_ads_84;
    private String is_from_messenger_ads_85;
    private String is_from_messenger_ads_86;
    private String is_from_messenger_ads_87;
    private String is_from_messenger_ads_88;
    private String is_from_messenger_ads_89;
    private String is_from_messenger_ads_90;
    private String is_from_messenger_ads_91;
    private String is_from_messenger_ads_92;
    private String is_from_messenger_ads_93;
    private String is_from_messenger_ads_94;
    private String is_from_messenger_ads_95;
    private String is_from_messenger_ads_96;
    private String is_from_messenger_ads_97;
    private String is_from_messenger_ads_98;
    private String is_from_messenger_ads_99;
    private String is_from_messenger_ads_100;
}
