/**
 * Error Code Constants
 * 
 * This file contains all error code constants that match the backend ErrorCode enum.
 * Use these constants instead of hardcoded strings to ensure type safety and consistency.
 */

// Common errors
export const NOT_FOUND = 'NOT_FOUND'
export const VALIDATION_ERROR = 'VALIDATION_ERROR'
export const UNAUTHORIZED = 'UNAUTHORIZED'
export const FORBIDDEN = 'FORBIDDEN'
export const ACCESS_DENIED = 'ACCESS_DENIED'
export const BAD_REQUEST = 'BAD_REQUEST'
export const CONFLICT = 'CONFLICT'
export const RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS'
export const INTERNAL_ERROR = 'INTERNAL_ERROR'
export const RUNTIME_ERROR = 'RUNTIME_ERROR'
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
export const TIMEOUT = 'TIMEOUT'
export const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
export const INTEGRATION_ERROR = 'INTEGRATION_ERROR'
export const ENDPOINT_NOT_FOUND = 'ENDPOINT_NOT_FOUND'
export const INVALID_REQUEST_BODY = 'INVALID_REQUEST_BODY'
export const UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE'
export const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
export const DATA_INTEGRITY_VIOLATION = 'DATA_INTEGRITY_VIOLATION'
export const OPTIMISTIC_LOCK = 'OPTIMISTIC_LOCK'
export const PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE'

// Authentication errors
export const BAD_CREDENTIALS = 'BAD_CREDENTIALS'
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED'
export const INVALID_TOKEN = 'INVALID_TOKEN'
export const TOKEN_INVALID_OR_EXPIRED = 'TOKEN_INVALID_OR_EXPIRED'
export const REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED'
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED'

// User errors
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS'
export const USER_NOT_FOUND = 'USER_NOT_FOUND'

// Tenant errors
export const TENANT_NOT_FOUND = 'TENANT_NOT_FOUND'
export const INVALID_TENANT_KEY = 'INVALID_TENANT_KEY'
export const INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION'
export const TENANT_STATUS_TRANSITION = 'TENANT_STATUS_TRANSITION'
export const TENANT_PROFILE_ERROR = 'TENANT_PROFILE_ERROR'
export const TENANT_INACTIVE = 'TENANT_INACTIVE'
export const ALREADY_MEMBER = 'ALREADY_MEMBER'
export const JOIN_REQUEST_ALREADY_SENT = 'JOIN_REQUEST_ALREADY_SENT'
export const INVITATION_PERMISSION_DENIED = 'INVITATION_PERMISSION_DENIED'
export const CANNOT_ASSIGN_ROLE = 'CANNOT_ASSIGN_ROLE'
export const USER_NOT_FOUND_FOR_INVITATION = 'USER_NOT_FOUND_FOR_INVITATION'
export const INVITATION_ALREADY_PENDING = 'INVITATION_ALREADY_PENDING'
export const INVITATION_INVALID = 'INVITATION_INVALID'
export const INVITATION_NOT_PENDING = 'INVITATION_NOT_PENDING'
export const INVITATION_EXPIRED = 'INVITATION_EXPIRED'
export const CANNOT_ACCEPT_INVITATION = 'CANNOT_ACCEPT_INVITATION'
export const INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND'
export const CANNOT_REJECT_INVITATION = 'CANNOT_REJECT_INVITATION'
export const CANNOT_REVOKE_INVITATION = 'CANNOT_REVOKE_INVITATION'
export const INVITATION_NOT_FOUND_IN_TENANT = 'INVITATION_NOT_FOUND_IN_TENANT'
export const TENANT_CONTEXT_MISSING = 'TENANT_CONTEXT_MISSING'
export const NOT_TENANT_MEMBER = 'NOT_TENANT_MEMBER'
export const TENANT_ID_REQUIRED = 'TENANT_ID_REQUIRED'
export const CANNOT_MANAGE_MEMBERS = 'CANNOT_MANAGE_MEMBERS'
export const CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND'
export const CANNOT_VIEW_JOIN_REQUESTS = 'CANNOT_VIEW_JOIN_REQUESTS'
export const CANNOT_APPROVE_JOIN_REQUESTS = 'CANNOT_APPROVE_JOIN_REQUESTS'
export const INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION'
export const JOIN_REQUEST_NOT_FOUND = 'JOIN_REQUEST_NOT_FOUND'
export const CANNOT_CANCEL_OTHERS_REQUEST = 'CANNOT_CANCEL_OTHERS_REQUEST'
export const CANNOT_CANCEL_NON_PENDING = 'CANNOT_CANCEL_NON_PENDING'
export const INVALID_JOIN_REQUEST = 'INVALID_JOIN_REQUEST'
export const CANNOT_CHANGE_OWNER_ROLE = 'CANNOT_CHANGE_OWNER_ROLE'
export const CANNOT_REMOVE_OWNER = 'CANNOT_REMOVE_OWNER'
export const NOT_TENANT_MEMBER_SELF = 'NOT_TENANT_MEMBER_SELF'
export const OWNER_MUST_TRANSFER = 'OWNER_MUST_TRANSFER'
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR'
export const CANNOT_ACCESS_TENANT = 'CANNOT_ACCESS_TENANT'
export const CANNOT_SUSPEND_TENANT = 'CANNOT_SUSPEND_TENANT'
export const CANNOT_RESUME_TENANT = 'CANNOT_RESUME_TENANT'
export const CANNOT_DELETE_TENANT = 'CANNOT_DELETE_TENANT'
export const TENANT_ID_NOT_FOUND = 'TENANT_ID_NOT_FOUND'
export const CANNOT_UPLOAD_LOGO = 'CANNOT_UPLOAD_LOGO'
export const CANNOT_UPDATE_LOGO = 'CANNOT_UPDATE_LOGO'
export const CANNOT_UPLOAD_AVATAR = 'CANNOT_UPLOAD_AVATAR'
export const CANNOT_CREATE_AVATAR_CATEGORY = 'CANNOT_CREATE_AVATAR_CATEGORY'

// License errors
export const LICENSE_NOT_FOUND = 'LICENSE_NOT_FOUND'
export const LICENSE_EXPIRED = 'LICENSE_EXPIRED'
export const LICENSE_INACTIVE = 'LICENSE_INACTIVE'

// Payment errors
export const PAYMENT_ERROR = 'PAYMENT_ERROR'
export const PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND'
export const PAYMENT_EXPIRED = 'PAYMENT_EXPIRED'
export const INVALID_PAYMENT_AMOUNT = 'INVALID_PAYMENT_AMOUNT'
export const BANK_API_ERROR = 'BANK_API_ERROR'
export const INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'

// Config errors
export const CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND'
export const CONFIG_ALREADY_EXISTS = 'CONFIG_ALREADY_EXISTS'
export const CONFIG_READONLY = 'CONFIG_READONLY'

// Conversation errors
export const CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND'
export const CANNOT_ASSIGN_CONVERSATION = 'CANNOT_ASSIGN_CONVERSATION'
export const CANNOT_RELEASE_CONVERSATION = 'CANNOT_RELEASE_CONVERSATION'
export const CANNOT_TAKEOVER_CONVERSATION = 'CANNOT_TAKEOVER_CONVERSATION'
export const CONVERSATION_ASSIGNED_TO_OTHER = 'CONVERSATION_ASSIGNED_TO_OTHER'
export const NOT_CONVERSATION_MEMBER = 'NOT_CONVERSATION_MEMBER'
export const CONVERSATION_IDS_REQUIRED = 'CONVERSATION_IDS_REQUIRED'
export const CANNOT_DELETE_CONVERSATIONS = 'CANNOT_DELETE_CONVERSATIONS'
export const BULK_DELETE_ERROR = 'BULK_DELETE_ERROR'

// Resource errors
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'

// File validation errors
export const INVALID_FILE_TYPE = 'INVALID_FILE_TYPE'
export const FILE_TOO_LARGE = 'FILE_TOO_LARGE'
export const FILE_EMPTY = 'FILE_EMPTY'
export const FILE_NULL = 'FILE_NULL'

// Agent validation errors
export const INVALID_AGENT_NAME = 'INVALID_AGENT_NAME'
export const INVALID_AGENT_EMAIL = 'INVALID_AGENT_EMAIL'
export const INVALID_AGENT_ROLE = 'INVALID_AGENT_ROLE'
export const INVALID_AGENT_MAX_CONCURRENT = 'INVALID_AGENT_MAX_CONCURRENT'
export const INVALID_AGENT_CURRENT_LOAD = 'INVALID_AGENT_CURRENT_LOAD'
export const AGENT_TENANT_ID_REQUIRED = 'AGENT_TENANT_ID_REQUIRED'

// Webhook validation errors
export const WEBHOOK_URL_EXISTS = 'WEBHOOK_URL_EXISTS'
export const INVALID_WEBHOOK_URL = 'INVALID_WEBHOOK_URL'
export const WEBHOOK_SIGNATURE_ERROR = 'WEBHOOK_SIGNATURE_ERROR'
export const WEBHOOK_TEST_FAILED = 'WEBHOOK_TEST_FAILED'

// Package validation errors
export const PACKAGE_ID_EXISTS = 'PACKAGE_ID_EXISTS'
export const PACKAGE_NOT_ACTIVE = 'PACKAGE_NOT_ACTIVE'

// Discount validation errors
export const DISCOUNT_CODE_EXISTS = 'DISCOUNT_CODE_EXISTS'

// Escalation errors
export const ESCALATION_TIER_NOT_FOUND = 'ESCALATION_TIER_NOT_FOUND'

// SLA errors
export const SLA_CONFIG_NOT_FOUND = 'SLA_CONFIG_NOT_FOUND'

// Routing rule errors
export const ROUTING_RULE_NOT_FOUND = 'ROUTING_RULE_NOT_FOUND'

// Environment config errors
export const ENVIRONMENT_CONFIG_NOT_FOUND = 'ENVIRONMENT_CONFIG_NOT_FOUND'

// Notification errors
export const NOTIFICATION_SEND_FAILED = 'NOTIFICATION_SEND_FAILED'

// Password validation errors
export const PASSWORD_CONFIRMATION_MISMATCH = 'PASSWORD_CONFIRMATION_MISMATCH'

// RSA key validation errors
export const RSA_PRIVATE_KEY_REQUIRED = 'RSA_PRIVATE_KEY_REQUIRED'
export const RSA_PUBLIC_KEY_REQUIRED = 'RSA_PUBLIC_KEY_REQUIRED'

// Network errors
export const NETWORK_ERROR = 'NETWORK_ERROR'

/**
 * Error code groups for easier checking
 */
export const AUTH_ERROR_CODES = [
  UNAUTHORIZED,
  BAD_CREDENTIALS,
  AUTHENTICATION_FAILED,
  INVALID_TOKEN,
  TOKEN_INVALID_OR_EXPIRED,
  REFRESH_TOKEN_EXPIRED,
  USER_NOT_AUTHENTICATED
]

export const VALIDATION_ERROR_CODES = [
  VALIDATION_ERROR,
  BAD_REQUEST,
  INVALID_REQUEST_BODY,
  INVALID_FILE_TYPE,
  FILE_TOO_LARGE,
  FILE_EMPTY,
  FILE_NULL,
  INVALID_AGENT_NAME,
  INVALID_AGENT_EMAIL,
  INVALID_AGENT_ROLE,
  INVALID_AGENT_MAX_CONCURRENT,
  INVALID_AGENT_CURRENT_LOAD,
  AGENT_TENANT_ID_REQUIRED,
  INVALID_WEBHOOK_URL,
  PACKAGE_NOT_ACTIVE,
  PASSWORD_CONFIRMATION_MISMATCH,
  RSA_PRIVATE_KEY_REQUIRED,
  RSA_PUBLIC_KEY_REQUIRED
]

export const FILE_ERROR_CODES = [
  INVALID_FILE_TYPE,
  FILE_TOO_LARGE,
  FILE_EMPTY,
  FILE_NULL
]

export const AGENT_ERROR_CODES = [
  INVALID_AGENT_NAME,
  INVALID_AGENT_EMAIL,
  INVALID_AGENT_ROLE,
  INVALID_AGENT_MAX_CONCURRENT,
  INVALID_AGENT_CURRENT_LOAD,
  AGENT_TENANT_ID_REQUIRED
]

export const WEBHOOK_ERROR_CODES = [
  WEBHOOK_URL_EXISTS,
  INVALID_WEBHOOK_URL,
  WEBHOOK_SIGNATURE_ERROR,
  WEBHOOK_TEST_FAILED
]

export const PACKAGE_ERROR_CODES = [
  PACKAGE_ID_EXISTS,
  PACKAGE_NOT_ACTIVE
]

export const PAYMENT_ERROR_CODES = [
  PAYMENT_ERROR,
  PAYMENT_NOT_FOUND,
  PAYMENT_EXPIRED,
  INVALID_PAYMENT_AMOUNT,
  INSUFFICIENT_BALANCE,
  BANK_API_ERROR
]

export const TENANT_ERROR_CODES = [
  TENANT_NOT_FOUND,
  TENANT_INACTIVE,
  TENANT_CONTEXT_MISSING,
  NOT_TENANT_MEMBER,
  CANNOT_ACCESS_TENANT
]

export const CONFLICT_ERROR_CODES = [
  CONFLICT,
  RESOURCE_ALREADY_EXISTS,
  EMAIL_ALREADY_EXISTS,
  WEBHOOK_URL_EXISTS,
  PACKAGE_ID_EXISTS,
  DISCOUNT_CODE_EXISTS
]

/**
 * Check if error code is in a specific group
 * @param {string} code - Error code to check
 * @param {Array<string>} group - Group of error codes
 * @returns {boolean}
 */
export function isErrorCodeInGroup(code, group) {
  return group.includes(code)
}

/**
 * Get error code group name
 * @param {string} code - Error code
 * @returns {string|null} Group name or null
 */
export function getErrorCodeGroup(code) {
  if (isErrorCodeInGroup(code, AUTH_ERROR_CODES)) return 'AUTH'
  if (isErrorCodeInGroup(code, VALIDATION_ERROR_CODES)) return 'VALIDATION'
  if (isErrorCodeInGroup(code, FILE_ERROR_CODES)) return 'FILE'
  if (isErrorCodeInGroup(code, AGENT_ERROR_CODES)) return 'AGENT'
  if (isErrorCodeInGroup(code, WEBHOOK_ERROR_CODES)) return 'WEBHOOK'
  if (isErrorCodeInGroup(code, PACKAGE_ERROR_CODES)) return 'PACKAGE'
  if (isErrorCodeInGroup(code, PAYMENT_ERROR_CODES)) return 'PAYMENT'
  if (isErrorCodeInGroup(code, TENANT_ERROR_CODES)) return 'TENANT'
  if (isErrorCodeInGroup(code, CONFLICT_ERROR_CODES)) return 'CONFLICT'
  return null
}
